from pynput import keyboard

ru_eng_keycodes = {
    "Й": keyboard.KeyCode(char="q"),
    "Ц": keyboard.KeyCode(char="w"),
    "У": keyboard.KeyCode(char="e"),
    "К": keyboard.KeyCode(char="r"),
    "Е": keyboard.KeyCode(char="t"),
    "Н": keyboard.KeyCode(char="y"),
    "Г": keyboard.KeyCode(char="u"),
    "Ш": keyboard.KeyCode(char="i"),
    "Щ": keyboard.KeyCode(char="o"),
    "З": keyboard.KeyCode(char="p"),
    "Х": keyboard.KeyCode(char="["),
    "Ъ": keyboard.KeyCode(char="]"),
    "Ф": keyboard.KeyCode(char="a"),
    "Ы": keyboard.KeyCode(char="s"),
    "В": keyboard.KeyCode(char="d"),
    "А": keyboard.KeyCode(char="f"),
    "П": keyboard.KeyCode(char="g"),
    "Р": keyboard.KeyCode(char="h"),
    "О": keyboard.KeyCode(char="j"),
    "Л": keyboard.KeyCode(char="k"),
    "Д": keyboard.KeyCode(char="l"),
    "Ж": keyboard.KeyCode(char=";"),
    "Э": keyboard.KeyCode(char="'"),
    "Я": keyboard.KeyCode(char="z"),
    "Ч": keyboard.KeyCode(char="x"),
    "С": keyboard.KeyCode(char="c"),
    "М": keyboard.KeyCode(char="v"),
    "И": keyboard.KeyCode(char="b"),
    "Т": keyboard.KeyCode(char="n"),
    "Ь": keyboard.KeyCode(char="m"),
    "Б": keyboard.KeyCode(char=","),
    "Ю": keyboard.KeyCode(char="."),
    "Ё": keyboard.KeyCode(char="/"),
}
